# Generated by Django 5.0.4 on 2024-04-19 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('reference_number', models.CharField(help_text='Уникальный номер ссылки для транзакции', max_length=100, unique=True, verbose_name='Номер ссылки')),
                ('debit_account', models.CharField(blank=True, help_text='Номер дебетового счета для транзакции', max_length=100, null=True, verbose_name='Дебетовый счет')),
                ('credit_account', models.CharField(blank=True, help_text='Номер кредитного счета для транзакции', max_length=100, null=True, verbose_name='Кредитный счет')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма транзакции', max_digits=12, verbose_name='Сумма')),
                ('is_successful', models.BooleanField(default=False, help_text='Указывает, была ли транзакция успешной', verbose_name='Успешная транзакция')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'bank_transactions',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('account_number', models.CharField(help_text='Уникальный номер счета', max_length=100, unique=True, verbose_name='Номер счета')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Текущий баланс на счете', max_digits=12, verbose_name='Баланс')),
                ('currency', models.CharField(blank=True, choices=[('Rs', 'Rupees')], default='Rs', help_text='Тип валюты', max_length=30, null=True, verbose_name='Валюта')),
                ('first_name', models.CharField(blank=True, help_text='Имя владельца счета', max_length=130, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия владельца счета', max_length=130, null=True, verbose_name='Фамилия')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Банковский счет',
                'verbose_name_plural': 'Банковские счета',
                'db_table': 'bank_accounts',
            },
        ),
    ]
