# Generated by Django 5.0.4 on 2024-04-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(blank=True, choices=[('Kzt', 'Tenge'), ('Kgs', 'Som'), ('Usd', 'Dollar'), ('Eur', 'Euro'), ('Rub', 'Ruble')], default='Kzt', help_text='Тип валюты', max_length=30, null=True, verbose_name='Валюта'),
        ),
    ]
